name:       haskell-notes
version:    0.0.1
synopsis:   Various Haskell notes
github:     jwiegley/notes
author:     John Wiegley
maintainer: johnw@newartisans.com
category:   System, Data, Nix
license:    BSD3

description:
  Various Haskell notes.

library:
  source-dirs: .
  ghc-options:
    - -Wall
  dependencies:
    - base                        >= 4.9 && < 5
    - Decimal
    - HUnit
    - QuickCheck
    - arrows
    - bytestring
    - constraints
    - containers
    - deepseq
    - free
    - hedgehog
    - lens
    - monad-par
    - mtl
    - multiset
    - pcre-heavy
    - row-types
    - tasty
    - tasty-hedgehog
    - tasty-hunit
    - time
    - transformers
