name:       haskell
version:    0.0.1
synopsis:   Various Haskell notes
github:     jwiegley/notes
author:     John Wiegley
maintainer: johnw@newartisans.com
category:   System, Data, Nix
license:    BSD3

description:
  Various Haskell notes.

library:
  source-dirs: .
  ghc-options:
    - -Wall
  dependencies:
    - base                        >= 4.9 && < 5
    - arrows
    - bytestring
    - constraints
    - containers
    - deepseq
    - lens
    - machines
    - mtl
    - monad-par
    - multiset
    - pcre-heavy
    - transformers
    - unordered-containers
    - QuickCheck
