(defun transform-by-lines (f)
  (goto-char (point-min))
  (while (not (eobp))
    (let* ((line-beg (line-beginning-position))
           (line-end (line-end-position))
           (line (buffer-substring line-beg line-end)))
      (delete-region line-beg line-end)
      (insert (funcall f line)))
    (forward-line)))
