Debugger entered--Lisp error: (void-function nil)
  nil((link :delete widget-leave-text :action gnus-widget-press-button :help-echo "Follow the link" :keymap (keymap (menu-bar keymap ...) (117 . gnus-article-copy-string)) :button-keymap nil :from #<marker (moves after insertion) at 7 in *Article INBOX*> :to #<marker at 48 in *Article INBOX*> :button-overlay #<overlay from 7 to 48 in *Article INBOX*>))
  widget-apply((link :delete widget-leave-text :action gnus-widget-press-button :help-echo "Follow the link" :keymap (keymap (menu-bar keymap ...) (117 . gnus-article-copy-string)) :button-keymap nil :from #<marker (moves after insertion) at 7 in *Article INBOX*> :to #<marker at 48 in *Article INBOX*> :button-overlay #<overlay from 7 to 48 in *Article INBOX*>) :button-face-get)
  widget-specify-button((link :delete widget-leave-text :action gnus-widget-press-button :help-echo "Follow the link" :keymap (keymap (menu-bar keymap ...) (117 . gnus-article-copy-string)) :button-keymap nil :from #<marker (moves after insertion) at 7 in *Article INBOX*> :to #<marker at 48 in *Article INBOX*> :button-overlay #<overlay from 7 to 48 in *Article INBOX*>) 7 48)
  widget-convert-text(link 7 48 7 48 :action gnus-widget-press-button :help-echo "Follow the link" :keymap (keymap (menu-bar keymap (Url\ Button menu-item "Url Button" ...)) (117 . gnus-article-copy-string)) :button-keymap nil)
  apply(widget-convert-text link 7 48 7 48 (:action gnus-widget-press-button :help-echo "Follow the link" :keymap (keymap (menu-bar keymap ...) (117 . gnus-article-copy-string)) :button-keymap nil))
  widget-convert-button(link 7 48 :action gnus-widget-press-button :help-echo "Follow the link" :keymap (keymap (menu-bar keymap (Url\ Button menu-item "Url Button" ...)) (117 . gnus-article-copy-string)) :button-keymap nil)
  gnus-article-add-button(7 48 gnus-button-reply #("\"Amazon.com Prime\" <primeclub@amazon.com>" 0 41 (original-date "Fri, 5 Aug 2011 19:21:49 +0000 (UTC)" face gnus-header-from)))
  gnus-article-add-buttons-to-head()
  gnus-treat-article(head)
  gnus-display-mime()
  gnus-article-prepare-display()
  gnus-article-prepare(253 nil)
  gnus-summary-display-article(253)
  gnus-summary-next-page(nil)
  call-interactively(gnus-summary-next-page nil nil)
