#!/bin/sh

TMPDIR=/tmp/ledger-pre-commit

# Checkout a copy of the current index into TMPDIR
git checkout-index --prefix=$TMPDIR/ -af

# Remove files which are no longer present in the index
git diff-index --cached --name-only --diff-filter=D -z HEAD | \
    (cd $TMPDIR; xargs --no-run-if-empty -0 rm -f --)

cd $TMPDIR

if [ ! -f Makefile ]; then
    tools/myacprep --local
fi

nice -n 20 make check && exit 0

exit 1
