; Translated by the Edison Design Group C++/C front end (version 4.4.1)
; LLVM IR generated by the BoostPro Computing LLVM back end
; Fri Aug 17 14:00:22 2012

; Source file information:
;
; ModuleID = '/Users/johnw/src/edg/test/stmk_return.c'

define i32 @main() {
entry:
  %retval = alloca i32, align 4
  store i32 0, i32* %retval, align 4
  %a = alloca i32, align 4
  %0 = load i32* %a, align 4
  %tobool = icmp ne i32 %0, 0
  br i1 %tobool, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  store i32 1, i32* %retval, align 4
  br label %return
  store i32 10, i32* %a, align 4
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  store i32 0, i32* %retval, align 4
  br label %return

return:                                           ; preds = %if.end, %if.then
  %1 = load i32* %retval, align 4
  ret i32 %1
}