with import <nixpkgs> { }; myEnvFun {
  name = "emacs-with-pkgs";
  buildInputs = with emacsPackagesNgGen emacs; [
    emacs
    ace-link
    ace-window
    aggressive-indent
    alert
    anaphora
    apiwrap
    async
    auctex
    auth-password-store
    auto-compile
    auto-yasnippet
    avy
    avy-zap
    back-button
    bbdb
    bbdb-vcard
    beacon
    biblio
    bm
    browse-at-remote
    browse-kill-ring
    button-lock
    calfw
    change-inner
    circe
    clipmon
    cmake-font-lock
    color-moccur
    command-log-mode
    company
    company-auctex
    company-coq
    company-ghc
    company-math
    company-quickhelp
    copy-as-format
    counsel
    counsel-gtags
    counsel-projectile
    crux
    csv-mode
    ctable
    dash
    dash-at-point
    debbugs
    deferred
    deft
    difflib
    diffview
    diminish
    dired-hacks-utils
    dired-ranger
    dired-toggle
    discover
    discover-my-major
    docker
    docker-compose-mode
    docker-tramp
    dockerfile-mode
    dumb-jump
    easy-kill
    ebdb
    edit-indirect
    elisp-docstring-mode
    elisp-refs
    elisp-slime-nav
    elmacro
    emojify
    epc
    epl
    erefactor
    esh-buf-stack
    esh-help
    eshell-autojump
    eshell-bookmark
    eshell-up
    eshell-z
    esxml
    eval-expr
    eval-in-repl
    evil
    expand-region
    eyebrowse
    f
    fancy-narrow
    flycheck
    flycheck-haskell
    flycheck-hdevtools
    flycheck-package
    fn
    focus
    font-lock-studio
    free-keys
    fringe-helper
    fullframe
    fuzzy
    ggtags
    gh
    ghc
    ghub
    ghub-plus
    gist
    git-annex
    git-link
    git-timemachine
    github-pullrequest
    gitpatch
    google-this
    graphviz-dot-mode
    haskell-mode
    helm
    helm-bibtex
    helm-dash
    helm-descbinds
    helm-describe-modes
    helm-firefox
    helm-google
    helm-navi
    helm-pass
    helpful
    highlight-defined
    highlight-numbers
    ht
    hydra
    hyperbole
    iedit
    iflipb
    imenu-list
    inf-ruby
    initsplit
    ipcalc
    ivy
    ivy-hydra
    ivy-pass
    ivy-rich
    jq-mode
    js2-mode
    js3-mode
    json-mode
    json-reformat
    json-snatcher
    know-your-http-well
    kv
    ledger-mode
    lentic
    lispy
    list-utils
    logito
    loop
    lsp-haskell
    lsp-mode
    lua-mode
    lusty-explorer
    m-buffer
    macrostep
    magit
    magit-imerge
    magithub
    makey
    malyon
    markdown-mode
    markdown-preview-mode
    marshal
    math-symbol-lists
    mc-extras
    mediawiki
    memory-usage
    minimap
    monitor
    multi-compile
    multi-term
    multifiles
    multiple-cursors
    muse
    names
    navi-mode
    nginx-mode
    nix-buffer
    nix-mode
    noflet
    nov
    oauth2
    ob-restclient
    olivetti
    org-bookmark-heading
    org-ref
    org-super-agenda
    org-web-tools
    origami
    outorg
    outshine
    ov
    package-lint
    packed
    pandoc-mode
    paradox
    paredit
    parent-mode
    parinfer
    parsebib
    parsec
    parsec
    pass
    password-store
    pcache
    pcre2el
    pdf-tools
    persistent-scratch
    pfuture
    phi-search
    phi-search-mc
    pkg-info
    popup
    popwin
    prodigy
    projectile
    python-mode
    rainbow-delimiters
    rainbow-mode
    redshank
    regex-tool
    repl-toggle
    request
    restclient
    reveal-in-osx-finder
    rich-minority
    riscv-mode
    s
    selected
    shackle
    shift-number
    slime
    smart-jump
    smart-newline
    smartparens
    smartscan
    smex
    sort-words
    sos
    spinner
    springboard
    sql-indent
    string-edit
    string-inflection
    super-save
    swiper
    tablist
    tagedit
    transpose-mark
    treemacs
    tuareg
    typo
    undo-tree
    use-package
    uuidgen
    vdiff
    vimish-fold
    visual-fill-column
    visual-regexp
    visual-regexp-steroids
    w3m
    web
    web-mode
    web-server
    websocket
    wgrep
    which-key
    whitespace-cleanup-mode
    with-editor
    worf
    writeroom-mode
    ws-butler
    yaml-mode
    yasnippet
    yasnippet-snippets
    z3-mode
    zencoding-mode
    zoom
    zoutline
    ztree
  ];
}
