#!/usr/bin/env python

import sys

from scapy import *

conf.iface='en0'
conf.verb=0

def handshake(host, port):
    # Send the initial SYN packet, the response will be a SYN+ACK which
    # indicates the connection is now "half-open"
    pkt = sr1(IP(dst=host)/TCP(dport=port,flags='S'))
    if not pkt or  not pkt.getlayer(TCP):
        return None
    
    if pkt.getlayer(TCP).flags != 0x12: # SYN+ACK
        pkt.show()
        sys.exit(1)

    # Respond to the SYN+ACK with an ACK packet.  This completes the
    # three-way TCP handshake, and we are now connected.  The packet we
    # receive in reply to protocols such as SMTP or SSH should be a
    # PSH+ACK containing the initial hello message.
    pkt = sr1(IP(dst=host)/TCP(dport=port,flags='A',ack=pkt.seq+1,seq=1))
    if not pkt or not pkt.getlayer(TCP):
        return None

    if pkt.getlayer(TCP).flags != 0x18: # PSH+ACK
        pkt.show()
        sys.exit(1)

    return pkt

resp = handshake(sys.argv[1], int(sys.argv[2]))

if resp:
    resp.show()
