  (defun my-auto-format ()
    (interactive)
    (save-restriction
      (save-excursion
        (let ((buf (buffer-string))
              write-contents-hooks)
          (when (executable-find "brittany")
            (unless (= 0 (call-process-region (point-min) (point-max)
                                              "brittany" t t nil "--indent=2"))
              (delete-region (point-min) (point-max))
              (insert buf)
              (set-buffer-modified-p nil)
              (when (and nil (executable-find "stylish-haskell"))
                (unless (= 0 (call-process-region (point-min) (point-max)
                                                  "stylish-haskell" t t))
                  (delete-region (point-min) (point-max))
                  (insert buf)
                  (set-buffer-modified-p nil)))))))))