SELECT
    A.COMPANYNAME,
    A.CONTACTNAME,
    DATA.PHONENO,
    DATA.FAXNO,
    A.EMAIL,
    A.WEBURL,
    A.SHIPTO_STREET,
    C.CITYNAME,
    PR.PROVINCENAME,
    P.POSTALCODENAME,
    CR.COUNTRYNAME,
    DATA.LASTORDERDATE
FROM
    (
        SELECT
            ACC.PHONENO,
            ACC.FAXNO,
            MIN(ORD.ORDERID)     AS ORDERID,
            MAX(ORD.CREATEDDATE) AS LASTORDERDATE
        FROM
            ACCOUNT ACC
        INNER JOIN ORDER ORD
        ON
            ORD.ACCOUNTID = ACC.ACCOUNTID
        GROUP BY
            ACC.PHONENO,
            ACC.FAXNO
    ) AS DATA
INNER JOIN ACCOUNT A
ON
    (
        A.PHONENO = DATA.PHONENO
    AND A.FAXNO = DATA.FAXNO
    )
LEFT JOIN ORDER O
ON
    DATA.ORDERID = O.ORDERID
LEFT JOIN PRINTORDER PO
ON
    PO.ORDERID = O.ORDERID
LEFT JOIN DOCUMENT D
ON
    D.DOCUMENTID = PO.DOCUMENTID
LEFT JOIN DOCUMENTTYPE DT
ON
    DT.DOCUMENTTYPEID = D.DOCUMENTTYPEID
LEFT JOIN POSTALCODE P
ON
    P.POSTALCODEID = A.SHIPTO_POSTALCODEID
LEFT JOIN CITY C
ON
    C.CITYID = P.CITYID
LEFT JOIN PROVINCE PR
ON
    PR.PROVINCEID = C.PROVINCEID
LEFT JOIN COUNTRY CR
ON
    CR.COUNTRYID = PR.COUNTRYID
ORDER BY
    COUNTRYNAME,
    PROVINCENAME,
    CITYNAME,
    POSTALCODENAME